Update d11.txt
Bladesheng/prison-architect-czech-translation pull request #5
Opened 2023-04-12 10:26 UTC by alium

další várka drobností a oprav

2023-04-12 10:32 UTC, alium reviewed
omylem smazáno jedno slovo, mělo by to být  teď opět v pořádku

2023-04-12 16:00 UTC, Bladesheng commented on ceskyprekladblade/data/language/d11.txt
> +object_CompostBin            KKompostér
"K" navíc

2023-04-12 16:00 UTC, Bladesheng commented on ceskyprekladblade/data/language/d11.txt
> +material_WallMedSec     Wall (střední ost.)
Zeď místo Wall

2023-04-12 16:00 UTC, Bladesheng commented on ceskyprekladblade/data/language/d11.txt
> +material_WallProtective Wall (žlutá)
Zeď místo Wall

2023-04-12 16:01 UTC, Bladesheng commented
Opět super práce 👍. Přidej si mě klidně na Steamu ať tě můžu dát do contributors na workshopu.

2023-04-12 16:53 UTC, alium commented
vidíš, chyby, kterých jsem si nevšiml. procházím to nějak tak postupně, jak hraju a nebo se mi tam nelíbí. opravím to, ať to můžeš commitnout

2023-04-12 17:58 UTC, alium reviewed
opraveny chyby

2023-04-12 21:00 UTC, Bladesheng commented on ceskyprekladblade/data/language/d11.txt
> +buildtoolbar_popup_obj_JailDoorJailDoorWhite      Barevné vězeňské dveře, které vám pomohou označit bloky pro choromyslné.
Asi překlep

2023-04-12 21:02 UTC, Bladesheng requested changes

2023-04-12 21:02 UTC, Bladesheng commented on ceskyprekladblade/data/language/d11.txt
> +buildtoolbar_popup_obj_JailDoorJailDoorWhite      Barevné vězeňské dveře, které vám pomohou označit bloky pro choromyslné.
Asi překlep

2023-04-13 04:52 UTC, alium reviewed
příště to líp zkontroluji :\

2023-04-13 06:14 UTC, Bladesheng approved these changes
Super 👍

2023-04-13 06:14 UTC, merged